name: Build

on:
  push:
    branches:
      - "main"

jobs:
  build-linux:
    uses: ./.github/workflows/build-common.yml
    with:
      runs-on: '["ubuntu-latest"]'

  build-windows:
    uses: ./.github/workflows/build-common.yml
    with:
      runs-on: '["windows-latest"]'
